// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package destination

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	ConfigAwsAccessKeyId     = "aws.accessKeyId"
	ConfigAwsDelayTime       = "aws.delayTime"
	ConfigAwsQueue           = "aws.queue"
	ConfigAwsQueueUseQueue   = "aws.queue.useQueue"
	ConfigAwsRegion          = "aws.region"
	ConfigAwsSecretAccessKey = "aws.secretAccessKey"
	ConfigAwsUrl             = "aws.url"
)

func (Config) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		ConfigAwsAccessKeyId: {
			Default:     "",
			Description: "AWSAccessKeyID is the amazon access key id",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigAwsDelayTime: {
			Default:     "0",
			Description: "MessageDelay represents the length of time, in seconds, for which a\nspecific message is delayed",
			Type:        config.ParameterTypeInt,
			Validations: []config.Validation{},
		},
		ConfigAwsQueue: {
			Default:     "{{ index .Metadata \"opencdc.collection\" }}",
			Description: "QueueName is the sqs queue name",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ConfigAwsQueueUseQueue: {
			Default:     "false",
			Description: "UseQueueName makes the connector always write to the specified queue name.\nOnly relevant when `aws.queue` is given as a sqs queue name.",
			Type:        config.ParameterTypeBool,
			Validations: []config.Validation{},
		},
		ConfigAwsRegion: {
			Default:     "",
			Description: "AWSRegion is the amazon sqs region",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigAwsSecretAccessKey: {
			Default:     "",
			Description: "AWSSecretAccessKey is the amazon secret access key",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigAwsUrl: {
			Default:     "",
			Description: "AWSURL is the URL for AWS (internal use only).",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
	}
}
