// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package common

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	DestinationConfigAwsAccessKeyId     = "aws.accessKeyId"
	DestinationConfigAwsDelayTime       = "aws.delayTime"
	DestinationConfigAwsQueue           = "aws.queue"
	DestinationConfigAwsRegion          = "aws.region"
	DestinationConfigAwsSecretAccessKey = "aws.secretAccessKey"
	DestinationConfigAwsUrl             = "aws.url"
)

func (DestinationConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		DestinationConfigAwsAccessKeyId: {
			Default:     "",
			Description: "AWSAccessKeyID is the amazon access key id",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		DestinationConfigAwsDelayTime: {
			Default:     "0",
			Description: "MessageDelay represents the length of time, in seconds, for which a\nspecific message is delayed",
			Type:        config.ParameterTypeInt,
			Validations: []config.Validation{},
		},
		DestinationConfigAwsQueue: {
			Default:     "",
			Description: "AWSQueue is the sqs queue name",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		DestinationConfigAwsRegion: {
			Default:     "",
			Description: "AWSRegion is the amazon sqs region",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		DestinationConfigAwsSecretAccessKey: {
			Default:     "",
			Description: "AWSSecretAccessKey is the amazon secret access key",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		DestinationConfigAwsUrl: {
			Default:     "",
			Description: "AWSURL is the URL for AWS (internal use only).",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
	}
}
