// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package common

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	SourceConfigAwsAccessKeyId       = "aws.accessKeyId"
	SourceConfigAwsQueue             = "aws.queue"
	SourceConfigAwsRegion            = "aws.region"
	SourceConfigAwsSecretAccessKey   = "aws.secretAccessKey"
	SourceConfigAwsUrl               = "aws.url"
	SourceConfigAwsVisibilityTimeout = "aws.visibilityTimeout"
	SourceConfigAwsWaitTimeSeconds   = "aws.waitTimeSeconds"
)

func (SourceConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		SourceConfigAwsAccessKeyId: {
			Default:     "",
			Description: "AWSAccessKeyID is the amazon access key id",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		SourceConfigAwsQueue: {
			Default:     "",
			Description: "AWSQueue is the sqs queue name",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		SourceConfigAwsRegion: {
			Default:     "",
			Description: "AWSRegion is the amazon sqs region",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		SourceConfigAwsSecretAccessKey: {
			Default:     "",
			Description: "AWSSecretAccessKey is the amazon secret access key",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		SourceConfigAwsUrl: {
			Default:     "",
			Description: "AWSURL is the URL for AWS (internal use only).",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		SourceConfigAwsVisibilityTimeout: {
			Default:     "0",
			Description: "VisibilityTimeout is the duration (in seconds) that the received messages\nare hidden from subsequent reads after being retrieved.",
			Type:        config.ParameterTypeInt,
			Validations: []config.Validation{},
		},
		SourceConfigAwsWaitTimeSeconds: {
			Default:     "10",
			Description: "WaitTimeSeconds is the duration (in seconds) for which the call waits for\na message to arrive in the queue before returning.",
			Type:        config.ParameterTypeInt,
			Validations: []config.Validation{},
		},
	}
}
